name: Node

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install pnpm
      run: npm i -g pnpm

    - run: pnpm i
    - run: pnpm recursive run test
