name: Test

on: [push, pull_request]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install and compile
      run: npm ci
    - name: Test
      run: npm test
