name: Test

on: [push, pull_request]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install and compile
      run: npm install
    - name: Test
      run: npm test
